# Generated by Django 2.0.2 on 2018-03-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('input_id', models.PositiveIntegerField(null=True)),
                ('tag_person', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.CharField(blank=True, max_length=256, null=True)),
                ('height', models.CharField(blank=True, max_length=256, null=True)),
                ('weight', models.CharField(blank=True, max_length=256, null=True)),
                ('race', models.CharField(blank=True, max_length=256, null=True)),
                ('caption', models.CharField(blank=True, max_length=256, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('picture', models.IntegerField(choices=[(0, 'Mine'), (1, 'Other')], default=0)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0)),
                ('angle', models.IntegerField(choices=[(0, 'Front'), (1, 'Back')], default=0)),
                ('bust_waist', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waist_hips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legs_body', models.DecimalField(decimal_places=2, max_digits=10)),
                ('body_waist', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shoulder_hips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_inputs',
            },
        ),
    ]
