# Generated by Django 2.0.2 on 2018-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
