# Generated by Django 2.0.2 on 2018-05-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180328_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='gender',
            field=models.IntegerField(choices=[(0, 'FeMale'), (1, 'Male')], default=0),
        ),
    ]
